### ISSUE TITLE
Wrong aggregate type when publishing event for customer creation

### ISSUE THREAD

**Issue by douggish** [eventuate-examples/eventuate-tram-core-dotnet-examples-customers-and-orders#9]
It doesn’t seem correct to use the customer ID as the aggregate type:

https://github.com/eventuate-examples/eventuate-tram-core-dotnet-examples-customers-and-orders/blob/433b8919e4878b2bff52ac90c297f92b9a74ecbc/CustomerService/Service/CustomerDataService.cs#L31

Shouldn't all customer events use the same aggregate type?

**Comment by cer** [comment]
Thanks. Fixed.
